# .github/workflows/alert.yml
name: 每分钟测试推送

# 触发器：定时任务 + 手动触发
on:
  schedule:
    # 每分钟执行一次 (UTC 时间)
    - cron: "* * * * *"
  workflow_dispatch: # 允许手动点击运行

# 作业定义
jobs:
  send-alert:
    runs-on: ubuntu-latest # 使用 Ubuntu 服务器运行

    steps:
      # 1. 获取仓库代码
      - uses: actions/checkout@v4

      # 2. 设置 Python 环境
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # 3. 安装依赖库
      - run: pip install requests

      # 4. 运行 Python 脚本
      - run: python send_alert.py
        env:
          # 将 GitHub Secrets 中的值注入为环境变量
          WECHAT_WEBHOOK: ${{ secrets.WECHAT_WEBHOOK }}
